  version: "3.7"

  services:
    app:
      build: .
      ports:
        - "9090:9090"
      networks:
        - s-network

    postgres:
      image: postgres:latest
      environment:
        POSTGRES_USER: yaryy
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: yaryy
      ports:
        - 5433:5432
      networks:
        - s-network
      volumes:
        - postgres-s-data:/var/lib/postgresql/data

  networks:
    s-network:
      driver: bridge

  volumes:
    postgres-s-data: