--INSERT INTO student (name, age) VALUES ('Pablo', 22);
--INSERT INTO student (name, age) VALUES ('Pedro', 25);
--INSERT INTO student (name, age) VALUES ('Hylio', 222);
--INSERT INTO student (name, age) VALUES ('Jmih', 12);